name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest  # Of windows-latest/macOS-latest als specifiek platform nodig is
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI
 
      - name: Installeer MAUI workloads
        run: dotnet workload install maui-android maui-windows

      - name: Restore Android for Grocery.App
        run: dotnet restore Grocery.App/Grocery.App.csproj -f net8.0-windows10.0.19041.0

      - name: Restore Android for Grocery.Core
        run: dotnet restore Grocery.Core/Grocery.Core.csproj -f net8.0-windows10.0.19041.0

      - name: Restore Android for Grocery.Core.Data
        run: dotnet restore Grocery.Core.Data/Grocery.Core.Data.csproj -f net8.0-windows10.0.19041.0

      - name: Restore Android for Grocery.App
        run: dotnet restore Grocery.App/Grocery.App.csproj -f net8.0-android

      - name: Restore Android for Grocery.Core
        run: dotnet restore Grocery.Core/Grocery.Core.csproj -f net8.0-android

      - name: Restore Android for Grocery.Core.Data
        run: dotnet restore Grocery.Core.Data/Grocery.Core.Data.csproj -f net8.0-android
 
      - name: Bouw de applicatie
        run: dotnet build --configuration Release --no-restore
 
      - name: Voer unit tests uit
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal